ac= input('digite qualquer coisa: ')
print(type(ac))
print('É apenas maiúsculo? ',ac.isupper())
print('É apenas minúsculo? ',ac.islower())
print('Possui apenas números? ',ac.isnumeric())
print('Possui Letras? ',ac.isalpha())
print('É alfa númerico?',ac.isalnum())
print('Possui apenasa Espaços? ',ac.isspace())
